<?php

/**
* Implementation of hook_permission().
*/
function helloworld_permission() 
{
	return array(
		'access helloworld' => array('title' => t('Access helloworld'))
	);
}

/**
* Implementation of hook_menu().
*/
function helloworld_menu() 
{
	$items = array();
	 
	$items['helloworld/sayhello'] = array(
		'title' => 'Hello World Test',
		'page callback' => 'say_hello_world',
		'access arguments' => array('access content'),
		'type' => MENU_CALLBACK,
	);
	
	$items['helloworld/formulaire'] = array(
		'title' => 'Hello World Formulaire',
		'page callback' => 'hello_world_myform',
		'access arguments' => array('access content'),
		'type' => MENU_CALLBACK,
	);
	 
	return $items;
}

function say_hello_world() 
{
	$query = db_select('users', 'u');
	 
	$query
		->condition('u.uid', 0, '<>')
		->fields('u', array('uid', 'name', 'status', 'created', 'access'))
		->range(0, 50);
	 
	$result = $query->execute();
	
	foreach ($result as $record) 
	{
		echo '<pre>';
		print_r($record);
		echo '</pre>';
	}
}