<?php

function getAllProjects ()
{
	// On récupère la liste des projets
	$sql = " SELECT * FROM projets_projet";
	// exécution de la requête
	$result = db_query(db_rewrite_sql($sql));

	// les données retournées sont stockées dans le tableau $allProjects
	$i = 0;
	while($proj = db_fetch_array($result))
	{
		$allProjects[$i] = $proj;
		$i++;
	}
	
	return theme('projects_list', $allProjects);
}

/**
 * Implementation of hook_menu().
 **/
 function projets_menu()
 {
	$items = array();

	$items['projects-list'] = array(
		'title' => "Liste de tous les projets",
		'page callback' => 'getAllProjects',
		'access arguments' => array('access content'),
		'type' => MENU_CALLBACK
	);

	return $items;
}

/**
 * Implementation of hook_theme().
 **/
function projets_theme()
{
	return array(
		'projects_list' => array(
			'template' => 'listeProjets',
			'arguments' => array('projets' => NULL),
		),
	);
}

?>